### ISSUE TITLE
io name of the instance port is wrong

### ISSUE THREAD

**Issue by raochl** [wswslzp/PyIOAssignment#1]
The posfix of pinFromCore and pinToCore is not consistence with the wire_m2c_name.  

In wire_m2c_name, you define `_A` as the wire for output port, and in the cell instance connection, you define `_D` as pinFromCore.

https://github.com/wswslzp/PyIOAssignment/blob/531045604cae408f029ef1f070e49aa0e98aa2eb/IO_assign/IOWriteFile.py#L61

https://github.com/wswslzp/PyIOAssignment/blob/531045604cae408f029ef1f070e49aa0e98aa2eb/IO_assign/IOWriteFile.py#L138-L140

**Comment by wswslzp** [comment]
This repo is not maintained anymore. If you wish to use it, you can fork the repo and keep developing.
